### ISSUE TITLE
Allow Abs Ingestion of tables to run asynchronously

### ISSUE THREAD

**Issue by AKST** [AKST/Australian-Address-Boundaries-Land-Property-Price-Database#27]
While it uses asyncio, it's basically synchronous. It steps through the main structures then the non main structures.  The non main structures are dependent on the main structures, the fact that foreign keys are inlined in the schema apply stuff is part of the problem.

This will be easier after #28 is done

## Tasks

- [ ] Perform revert foreign keys at the start of the operation
- [ ] Truncate all tables
- [ ] Ingest each table in parallel for main structures
- [ ] Ingest each table in parallel for non main structures
- [ ] Reapply foreign keys
