### ISSUE TITLE
Restructure ABS Schema with event sourcing in mind

### ISSUE THREAD

**Issue by AKST** [AKST/Australian-Address-Boundaries-Land-Property-Price-Database#32]
In particular the electoral divisions that have different information for different years. 

## Tasks

- Create seperate tables for event based tables
    - [ ] Create table for `abs.lga`
    - [ ] Create table for `abs.state_electoral_division`
- Create seperate staging schema for event based tables
   - [ ] Create schema `abs_raw` place in `001_APPLY_init.sql`
   - [ ] Create task to assemble the `abs.lga` and run in `tasks/ingest_abs.py`
   - [ ] Create task to assemble the `abs.state_electoral_division` and run in `tasks/ingest_abs.py`

## Event Schema
https://github.com/AKST/Australian-Address-Boundaries-Land-Property-Price-Database/blob/4c55328fab080459f761457661421b7248225273/sql/meta/schema/001_APPLY_init.sql#L28-L34

### Electoral Division Tables
https://github.com/AKST/Australian-Address-Boundaries-Land-Property-Price-Database/blob/4c55328fab080459f761457661421b7248225273/sql/abs/schema/003_APPLY_non_mainstructures.sql#L11-L49

### Lga Tables
https://github.com/AKST/Australian-Address-Boundaries-Land-Property-Price-Database/blob/4c55328fab080459f761457661421b7248225273/sql/abs/schema/003_APPLY_non_mainstructures.sql#L51-L89

**Comment by AKST** [comment]
We can probably just do these are material views tbh.
