### ISSUE TITLE
Setup property description parsing for `nsw_lrs.property_description`

### ISSUE THREAD

**Issue by AKST** [AKST/Australian-Address-Boundaries-Land-Property-Price-Database#42]
blocked by #41 

## Subtasks

- [x] Version the property description
- [x] Update `LandParcel` to extract the `lot` `plan` and `section`
- [x] Handle Strat Plan parcel ids.
- Update database
  - [x] Populate `nsw_lrs.parcel`
  - [x] Maybe make a new relation for strata lots
  - [x] Link parcels to properties
